### ISSUE TITLE
Offset && Scroll && client

### ISSUE THREAD

**Issue by huyoooooooo** [huyoooooooo/blog#6]
对元素自身大小、相对位置等进行计算时，通常绕不开 offset、client、scroll三个属性。

## offset

+ 和自身大小相关 offsetWidth、offsetHeight
  > 一个典型的 offsetWidth 是测量包含元素的边框 (border)、水平线上的内边距 (padding)、竖直方向滚动条 (scrollbar)（如果存在的话）、以及 CSS 设置的宽度 (width) 的值。

+ 和相对位置有关 offsetTop、offsetLeft、offsetParent
  - offsetParent 指向最近的（指包含层级上的最近）包含该元素的定位元素 (position: relative/absolute) 或最近的 table, td, th, body 元素
  - 若当前元素被隐藏(display: none) 或者固定元素(position: fixed)时, offsetParent 值为 null
  - offsetLeft 和 offsetTop 都是相对 offsetParent 内边距边界

+ offsetX, offsetY
  - offsetX：鼠标点击位置相对于触发事件对象的水平距离
  - offsetY：鼠标点击位置相对于触发事件对象的垂直距

所有属性的获取值只读，且为整数。

## client

+ clientWidth、clientHeight  
  > 只读属性 Element.clientWidth 对于内联元素以及没有 CSS 样式的元素为 0；否则，它是元素内部的宽度（以像素为单位）。该属性包括内边距（padding），但不包括边框（border）、外边距（margin）和垂直滚动条（如果存在）

+ clientTop、clientLeft
  > 表示一个元素的左边框的宽度，以像素表示

+ clientX, clientY
  - 参照点：浏览器内容区域左上角
  - clientX：鼠标点击位置相对于浏览器可视区域的水平偏移量（不会计算水平滚动的距离）
  - clientY：鼠标点击位置相对于浏览器可视区域的垂直偏移量（不会计算垂直滚动条的距离）

### 计算滚动条宽度
  ```javascript
  function computedScrollbarWidth() {
    const outer = document.createElement('div')
    const inner = document.createElement('div')

    outer.style.overflow = 'scroll'
    outer.appendChild(inner)

    document.body.appendChild(outer)

    let scrollbarWidth = outer.offsetWidth - inner.offsetWidth
    document.body.removeChild(outer)
    return scrollbarWidth
  }

  computedScrollbarWidth()      // Chorme -- 17px
  ```

### 自定义滚动条样式
  <details>
    <summary>伪类选择器主要有</summary>

    + ::webkit-scrollbar —— 整个滚动条
    + ::webkit-scrollbar-button —— 滚动条上的按钮（上下箭头）
    + ::webkit-scrollbar-thumb —— 滚动条上的滚动滑块
    + ::webkit-scrollbar-track —— 滚动条轨道
    + ::webkit-scrollbar-track-piece —— 滚动条没有滑块的轨道部分
    + ::webkit-scrollbar-corner —— 当同时有垂直滚动和水平滚动条交汇的部分。

  </details>

  ```css
  .scroll-y {
    &::-webkit-scrollbar {          /* 滚动条 */
      width: 6px;
    }
    &::-webkit-scrollbar-thumb {    /* 滑块颜色 */
      background-color: #0003;
      border-radius: 10px;
    }
    &::-webkit-scrollbar-thumb:hover {
      background-color: #909399;
      box-shadow: inset 0 0 5px rgba(0, 0, 0, 0.1);
    }
    &::-webkit-scrollbar-track {    /* 滚动条的滑轨背景颜色 */
      border-radius: 10px;
    }
  }
  ```

### scrollTop, scrollLeft
> 一个元素的 scrollTop 值是这个元素的内容顶部（卷起来的）到它的视口可见内容（的顶部）的距离的度量。

注：设置scrollTop的值小于 0，scrollTop 被设为0；如果设置了超出这个容器可滚动的值，scrollTop 会被设为最大值。

```javascript
outer.scrollTo({
  top: 100,
  behavior: 'smooth'    // 平滑滚动
})
```
